VMO-3449 allow nested context objects to be used in array functions
FLOIP/expression-evaluator pull request #7
Opened 2021-02-05 05:37 UTC by seifertk

"@(IN(groups.group, contact.groups))"

This should work ,but doesn't because:
contact.groups is being coerced into a JSON string.

Solution:
Don't cast object-like values into JSON immediately, do it just-in-time.
Allow the object-like values to be iterated over and expose any child objects value

New test + old tests pass locally.

2021-02-07 22:35 UTC, GrimFunction approved these changes

2021-02-12 23:21 UTC, bzabos commented on dist/Evaluator/NodeEvaluator/MemberNodeEvaluator/MemberObject.d.ts
> +    toJSON(): string;
Don't most toJSON()s return a vanilla JS object? Or is that just Backbone?

2021-03-30 19:19 UTC, AlteaDown commented on dist/Evaluator/NodeEvaluator/MemberNodeEvaluator/MemberObject.d.ts
> +    toJSON(): string;
It's usually a String.

2021-03-30 19:23 UTC, AlteaDown requested changes
I believe you need to pull master, and then update how imports work, so that you replace default imports with named imports from `index.ts`.

2021-04-01 02:22 UTC, merged